### ISSUE TITLE
kali & dnsmasq

### ISSUE THREAD

**Issue by web-differently12** [OlivierProTips/linux_install#1]
bonjour, je n'arrive pas a installé dnsmasq correctement 
j'ai toujours cette erreur 
<img width="827" alt="Screenshot 2023-10-15 at 12 02 04" src="https://github.com/OlivierProTips/linux_install/assets/132818618/5925b556-edcc-4b15-8d9a-b90f10d1c51a">
<img width="1091" alt="Screenshot 2023-10-15 at 12 02 33" src="https://github.com/OlivierProTips/linux_install/assets/132818618/28a64c41-091f-4221-91e6-aac410d927cd">

**Comment by web-differently12** [comment]
<img width="932" alt="Screenshot 2023-10-15 at 12 13 45" src="https://github.com/OlivierProTips/linux_install/assets/132818618/2948ae84-2735-4bfd-a551-64e986cf5eb6">
<img width="1115" alt="Screenshot 2023-10-15 at 12 14 31" src="https://github.com/OlivierProTips/linux_install/assets/132818618/0daebeff-d248-4048-979c-28b343538cf8">

**Comment by OPTips** [comment]
Hello,

Dans les nouvelles versions de Kali, dnsmasq est intégré à NetworkManager, donc il ne faut plus utiliser le paquet dnsmasq.

L'erreur que tu as est qu'il est déjà lancé. Désinstalle dnsmasq (apt remove dnsmasq) et regarde cette doc : https://github.com/OlivierProTips/HackNotes/blob/main/dnsmasq.md

Tiens-moi au courant 😉

**Comment by web-differently12** [comment]
hello merci olivier, mais jai reussi a trouvé une autres solutions 
sudo nano /etc/rc0.rc.local 
et ça 
je vais faire un snap et test ça 
<img width="1123" alt="Screenshot 2023-10-15 at 14 27 22" src="https://github.com/OlivierProTips/linux_install/assets/132818618/5fa6e9d3-8aaa-42a3-97b3-1768c965fadb">

**Comment by OPTips** [comment]
Ok. Tu me diras si ça marche.

**Comment by web-differently12** [comment]
j'ai l'impression que j'ai un cache qui ne renouvelle pas 
<img width="1151" alt="Screenshot 2023-10-15 at 15 07 20" src="https://github.com/OlivierProTips/linux_install/assets/132818618/e10aab5d-63bd-460b-a5e6-0b3b2f614e72">
<img width="1107" alt="Screenshot 2023-10-15 at 15 08 28" src="https://github.com/OlivierProTips/linux_install/assets/132818618/4259f472-dc09-4123-adde-a495127011c2">

**Comment by OPTips** [comment]
Tu as redémarré le service NetworkManager ?

**Comment by web-differently12** [comment]
oui, mais toujours pareil 
je fait refaire une nouvelle machine
